### ISSUE TITLE
android clarifai implementing Exception

### ISSUE THREAD

**Issue by manojkumarmeerut** [Clarifai/clarifai-android-starter#11]
com.clarifai.android.starter.api.v2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.clarifai.android.starter.api.v2, PID: 22534
                                                                                     java.lang.RuntimeException: Unable to create application com.clarifai.android.starter.api.v2.App: clarifai2.exception.ClarifaiException: java.util.concurrent.ExecutionException: clarifai2.exception.ClarifaiException: API call to refresh token unsuccessful
                                                                                     	Provided AppID: cc42b10022ba4881a69b84e3bc963992
                                                                                     	Provided AppSecret: NhujL3Zy_79qgEeik-XlKNFeS6t-0TR142hUqnd0
                                                                                     	Provided BaseURL: https://api.clarifai.com/
                                                                                     	Status code: 401
                                                                                     	Message: Unauthorized
                                                                                     	Details: {"status":{"code":11002,"description":"Invalid credentials","details":"invalid client ID (cc42b10022ba4881a69b84e3bc963992) and secret (NhujL3Zy_79qgEeik-XlKNFeS6t-0TR142hUqnd0)"}}
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
                                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:157)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5437)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                      Caused by: clarifai2.exception.ClarifaiException: java.util.concurrent.ExecutionException: clarifai2.exception.ClarifaiException: API call to refresh token unsuccessful
                                                                                     	Provided AppID: cc42b10022ba4881a69b84e3bc963992
                                                                                     	Provided AppSecret: NhujL3Zy_79qgEeik-XlKNFeS6t-0TR142hUqnd0
                                                                                     	Provided BaseURL: https://api.clarifai.com/
                                                                                     	Status code: 401
                                                                                     	Message: Unauthorized
                                                                                     	Details: {"status":{"code":11002,"description":"Invalid credentials","details":"invalid client ID (cc42b10022ba4881a69b84e3bc963992) and secret (NhujL3Zy_79qgEeik-XlKNFeS6t-0TR142hUqnd0)"}}
                                                                                         at clarifai2.api.BaseClarifaiClient.refresh(BaseClarifaiClient.java:120)
                                                                                         at clarifai2.api.BaseClarifaiClient.getCredential(BaseClarifaiClient.java:84)
                                                                                         at clarifai2.api.BaseClarifaiClient.<init>(BaseClarifaiClient.java:77)
                                                                                         at clarifai2.api.ClarifaiClientImpl.<init>(ClarifaiClientImpl.java:51)
                                                                                         at clarifai2.api.ClarifaiBuilder.buildSync(ClarifaiBuilder.java:75)
                                                                                         at com.clarifai.android.starter.api.v2.App.onCreate(App.java:51)
                                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4727)
                                                                                         	... 8 more
                                                                                      Caused by: java.util.concurrent.ExecutionException: clarifai2.exception.ClarifaiException: API call to refresh token unsuccessful
                                                                                     	Provided AppID: cc42b10022ba4881a69b84e3bc963992
                                                                                     	Provided AppSecret: NhujL3Zy_79qgEeik-XlKNFeS6t-0TR142hUqnd0
                                                                                     	Provided BaseURL: https://api.clarifai.com/
                                                                                     	Status code: 401
                                                                                     	Message: Unauthorized
                                                                                     	Details: {"status":{"code":11002,"description":"Invalid credentials","details":"invalid client ID (cc42b10022ba4881a69b84e3bc963992) and secret (NhujL3Zy_79qgEeik-XlKNFeS6t-0TR142hUqnd0)"}}
                                                                                         at java.util.concurrent.FutureTask.report(FutureTask.java:94)
                                                                                         at java.util.concurrent.FutureTask.get(FutureTask.java:164)
                                                                                         at java.util.concurrent.AbstractExecutorService.doInvokeAny(AbstractExecutorService.java:163)
                                                                                         at java.util.concurrent.AbstractExecutorService.invokeAny(AbstractExecutorService.java:185)
                                                                                         at clarifai2.api.BaseClarifaiClient.refresh(BaseClarifaiClient.java:92)
                                                                                         	... 15 more
                                                                                      Caused by: clarifai2.exception.ClarifaiException: API call to refresh token unsuccessful
                                                                                     	Provided AppID: cc42b10022ba4881a69b84e3bc963992
                                                                                     	Provided AppSecret: NhujL3Zy_79qgEeik-XlKNFeS6t-0TR142hUqnd0
                                                                                     	Provided BaseURL: https://api.clarifai.com/
                                                                                     	Status code: 401
                                                                                     	Message: Unauthorized
                                                                                     	Details: {"status":{"code":11002,"description":"Invalid credentials","details":"invalid client ID (cc42b10022ba4881a69b84e3bc963992) and secret (NhujL3Zy_79qgEeik-XlKNFeS6t-0TR142hUqnd0)"}}
                                                                                         at clarifai2.api.BaseClarifaiClient$2.call(BaseClarifaiClient.java:108)
                                                                                         at clarifai2.api.BaseClarifaiClient$2.call(BaseClarifaiClient.java:93)
                                                                                     	at java.util.concurrent.FutureTask.run(FutureTa

Please tell me what is happening with my code.
what should i do?

**Comment by eddiezane** [comment]
Were you able to figure this out? Did you confirm your credentials are entered correctly?
